# Generated by Django 5.2 on 2025-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QArecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answre', models.TextField()),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
